### ISSUE TITLE
In which role do we configure physical interface?

### ISSUE THREAD

**Issue by ochko** [reallyenglish/ansible-role-virtual-interface#19]
For example we might need to configure a physical interface:

/etc/hostname.vr1:
```
up
group ingress
```

The role name is `virtual-interface`. But should we use it for physical interfaces too?

**Comment by trombik** [comment]
Short answer: no.

It was named for a reason. There are some assumptions when you run `ansible`. besides an obvious requirement to install `python` and `sshd`, `ansible` assumes that the network interface is fully configured. The default interface on a host is usually configured at the initial installation phase, either DHCP or static, by bootstrap script. You rarely need to configure the default interface and you should not because when you reconfigure the default interface, which is almost always a physical interface, the interface would be restarted, which would subsequently break the SSH connection in which `ansible` runs. with `ansible-role-virtual-interface`, it would never happen (unless, of course, you seriously mess up the configuration). Theoretically, it is impossible to bootstrap a bare-bone installation with `ansible`. A good example is a host that is connected to the default network via `pppoe(4)`

Despite these culprits, there are cases where you want to configure physical interfaces. There should be something like `ansible-role-physical-interface", which configures physical network interfaces.

## Considerations

* the role should implement a mechanism to prevent users from accidentally re-configuring the interface that is being used by `ansible`
* dependency handling would be tricky, i.e. virtual interfaces usually depends on physical interfaces, but not always, not all changes needs full reconfiguration, or restart, of the interface
* it would be nice for `ansible` to have an ability to survive temporary network disruption (this would be challenging because it would add extra dependencies to the requirement and need serious surgery to the core of `ansible`)
